from __future__ import annotations

import re
from pathlib import Path

TEXT_SUFFIXES={".py",".js",".jsx",".ts",".tsx",".go",".rs",".java",".kt",".rb",".php",".cs",".sql",".yml",".yaml",".json",".toml",".md",".ini",".cfg"}

def _rel(root,p): return p.relative_to(root).as_posix()
def _files(root): return sorted(p for p in root.rglob("*") if p.is_file() and ".git" not in p.parts and p.suffix.lower() in TEXT_SUFFIXES)
def _sig(kind,path,detail): return {"kind":kind,"locator":path,"detail":detail,"state":"PARTIAL","confidence":"MEDIUM"}
def _pack(items,unknown):
    seen=set(); out=[]
    for x in items:
        k=(x["kind"],x["locator"],x["detail"])
        if k not in seen: seen.add(k); out.append(x)
    return {"signals":out[:200],"confidence":"PARTIAL" if out else "UNVERIFIED","unknowns":[unknown]}

def extract_wave_d(root:Path)->dict:
    migration=[]; interface=[]; license_ip=[]
    for p in _files(root):
        path=_rel(root,p); low=p.read_text(encoding='utf-8',errors='replace').lower(); name=p.name.lower()
        if re.search(r"\b(migration|migrate|alembic|flyway|liquibase|schema change|ddl|alter table|create table|drop table|rollback|downgrade|backfill)\b",low) or 'migration' in path.lower(): migration.append(_sig('migration_surface',path,'database/schema migration or rollback signal observed'))
        if re.search(r"\b(backward compatible|forward compatible|zero downtime|expand contract|dual write|backfill|irreversible)\b",low): migration.append(_sig('migration_compatibility',path,'migration compatibility/zero-downtime/irreversibility signal observed'))
        if re.search(r"\b(openapi|swagger|json schema|graphql|protobuf|proto3|avro|event schema|api version|versioned api)\b",low) or any(x in name for x in ('openapi','swagger','.proto')): interface.append(_sig('contract_surface',path,'machine-readable or documented interface contract signal observed'))
        if re.search(r"\b(consumer|producer|compatibility|breaking change|deprecate|version drift|contract test)\b",low): interface.append(_sig('compatibility_signal',path,'producer/consumer compatibility or contract-drift signal observed'))
        if name.startswith(('license','copying','notice')) or re.search(r"\b(spdx-license-identifier|copyright|license|licence|attribution|third-party|third party|generated by|ai-generated|code provenance|source origin)\b",low): license_ip.append(_sig('license_or_origin',path,'license/attribution/source-origin/provenance signal observed'))
    return {
      'migration':_pack(migration,'static repository evidence does not prove migration reversibility, data preservation, forward/backward compatibility or zero-downtime behavior'),
      'interface':_pack(interface,'static repository evidence does not prove deployed producer/consumer compatibility, absence of contract drift or safe rollout across repositories/services'),
      'license_ip':_pack(license_ip,'static repository evidence does not establish legal ownership, license compatibility, attribution completeness or intellectual-property clearance'),
    }
